# -*- coding: utf-8 -*-
"""Music_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lganIhYgc5Ng2rzZKyURUTkCyKiIdk3p
"""

!pip install Spotipy

import pandas as pd
import numpy as np
import csv
import sys
import spotipy
import spotipy.util as util
from spotipy.oauth2 import SpotifyClientCredentials
import spotipy.oauth2 as oauth2

SPOTIPY_CLIENT_ID = "ba0aefea59a44616bc6703a7294d312d"
SPOTIPY_CLIENT_SECRET = "989d552704124fe086005b3851f5a94b"
redirect_uri='http://localhost:8888/callback/'

client_credentials_manager = SpotifyClientCredentials(client_id=SPOTIPY_CLIENT_ID, client_secret=SPOTIPY_CLIENT_SECRET)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

from google.colab import files
uploaded = files.upload()

names = pd.read_csv("Artists - Sheet1.csv")
names

names_df =  pd.DataFrame({'artists' : ["Led Zeppelin","Queen","Rush","Pink Floyd","AC/DC","The Beatles","Black Sabbath","The Rolling Stones","Metallica","Iron Maiden",
"Deep Purple","Guns N' Roses","Who","Def Leppard","Van Halen","Kiss","Aerosmith","Eagles","Yes","Jimi Hendrix","Bob Dylan","Thin Lizzy","David Bowie","Bon Jovi","U2",
"Foo Fighters","Motorhead","Genesis","Judas Priest","Nirvana","Fleetwood Mac","Tool","Bruce Springsteen","Slade","Lynyrd Skynyrd","The Doors","Creedence Clearwater Revival",
"Chicago","Uriah Heep","Status Quo","Marillion","Pearl Jam","Rainbow","Motley Crue","Cream","Journey","Ramones","ZZ Top","King Crimson","Roxy Music"]})

nm_df = np.repeat(names_df['artists'], 20)
nm_df

track_lis = []
for artst in names_df.iterrows():
  print(artst[1])
  results = sp.search(q='artist:' + artst[1], limit=20)
  for idx, track in enumerate(results['tracks']['items']):
    print(idx, track['name'])
    track_lis.append(track['name'])

from google.colab import files
df = pd.DataFrame(list(zip(nm_df, track_lis)), columns=['Artists', 'Tracks'])
df.to_csv('Tracks.csv', sep=',')
files.download('Tracks.csv')

coverimg_lis = []
for artst in names_df.iterrows():
  results = sp.search(q='artist:' + artst[1], type='artist')
  items = results['artists']['items']
  if len(items) > 0:
    artist = items[0]
    print(artist['name'], artist['images'][0]['url'])
    coverimg_lis.append(artist['images'][0]['url'])

from google.colab import files
df = pd.DataFrame(list(zip(names_df['artists'], coverimg_lis)), columns=['Artists', 'CoverArt'])
df.to_csv('CoverArt.csv', sep=',')
files.download('CoverArt.csv')

l = []
for artst in names_df.iterrows():
  result = sp.search(q='artist:' + artst[1]) 
  fin_result = result['tracks']['items'][0]['artists']
  artist_uri = fin_result[0]['uri']
  print(fin_result)
  print(artist_uri)
  l.append(artist_uri)
print(l)

from google.colab import files
df = pd.DataFrame(l, columns=['Artist_URI'])
df.to_csv('Artist_URI - Sheet1.csv', sep=',')
files.download('Artist_URI - Sheet1.csv')

from google.colab import files
uploaded = files.upload()

artist_uri = pd.read_csv("Artist_URI - Sheet1.csv")
artist_uri

artists_uri_ls = ["36QJpDe2go2KgaRleHCDTp",
"1dfeR4HaWDbWqFHLkxsg1d",
"2Hkut4rAAyrQxRdof7FVJq",
"0k17h0D3J5VfsdmQ1iZtE9",
"711MCceyCBcFnzjGY4Q7Un",
"3WrFJ7ztbogyGnTHbHJFl2",
"5M52tdBnJaKSvOpJGz8mfZ",
"22bE4uQ6baNwSHPVcDxLCe",
"2ye2Wgw4gimLv2eAKyk1NB",
"6mdiAmATAx73kdxrNrnlao",
"568ZhdwyaiCyOGJRtNYhWf",
"3qm84nBOXUEQ2vnTfUTTFC",
"67ea9eGLXYMsO2eYQRui3w",
"6H1RjVyNruCmrBEWRbD0VZ",
"2cnMpRsOVqtPMfq7YiFE6K",
"07XSN3sPlIlB2L2XNcTwJw",
"7Ey4PD4MYsKc5I2dolUwbH",
"0ECwFtbIWEVNwjlrfc6xoL",
"7AC976RDJzL2asmZuz7qil",
"776Uo845nYHJpNaStv1Ds4",
"74ASZWbe4lXaubB36ztrGX",
"6biWAmrHyiMkX49LkycGqQ",
"0oSGxfWSnnOXhD2fKuz2Gy",
"58lV9VcRSjABbAbfWS6skp",
"51Blml2LZPmy7TTiAg47vQ",
"7jy3rLJdDQY21OgRLCZ9sD",
"1DFr97A9HnbV3SKTJFu62M",
"3CkvROUTQ6nRi9yQOcsB50",
"2tRsMl4eGxwoNabM08Dm4I",
"6olE6TJLqED3rqDCT0FyPh",
"08GQAI4eElDnROBrJRGE0X",
"2yEwvVSSSUkcLeSTNyHKh8",
"3eqjTLE0HfPfh78zjh6TqT",
"10n5lhNDoSMUHWLlnST1yw",
"4MVyzYMgTwdP7Z49wAZHx0",
"22WZ7M8sxp5THdruNY3gXt",
"3IYUhFvPQItj6xySrBmZkd",
"3iDD7bnsjL9J4fO298r0L0",
"45O9BwPMyywM755SYUK0sP",
"4gIdjgLlvgEOz7MexDZzpM",
"7ai5TWiOG8g9Hds5AATS28",
"1w5Kfo2jwwIPruYS2UWh56",
"6SLAMfhOi7UJI0fMztaK0m",
"0cc6vw3VN8YlIcvr1v7tBL",
"74oJ4qxwOZvX6oSsu1DGnw",
"0rvjqX7ttXeg3mTy8Xscbt",
"1co4F2pPNH8JjTutZkmgSm",
"2AM4ilv6UzW0uMRuqKtDgN",
"7M1FPw29m5FbicYzS2xdpi",
"3fhOTtm0LBJ3Ojn4hIljLo"]

all_artst_lst_albm = []
for artst_uri in artists_uri_ls:
  sp_albums = sp.artist_albums(artst_uri, album_type='album', limit=15)
  print(sp_albums)
  all_artst_lst_albm.append(sp_albums)

print(all_artst_lst_albm[0])
sp_albums = all_artst_lst_albm[0]

sgl_album_names = []
sgl_album_uris = []
for i in range(len(sp_albums['items'])):
    sgl_album_names.append(sp_albums['items'][i]['name'])
    sgl_album_uris.append(sp_albums['items'][i]['uri'])    
sgl_album_names

sgl_album_uris

albums = {}
album_count = 0
for i in sgl_album_uris: 
    SongsInalbum(i)
    print("Album - " + str(sgl_album_names[album_count]))
    album_count+=1

def SongsInalbum(uri):
    album = uri 
    albums[album] = {} 
    albums[album]['album'] = [] 
    albums[album]['track_number'] = []
    albums[album]['id'] = []
    albums[album]['name'] = []
    albums[album]['uri'] = []
    albums[album]['duration_ms'] = []
    albums[album]['preview_url'] = []

    tracks = sp.album_tracks(album) 
    
    for n in range(len(tracks['items'])):
            albums[album]['album'].append(sgl_album_names[album_count]) 
            albums[album]['track_number'].append(tracks['items'][n]['track_number'])
            albums[album]['id'].append(tracks['items'][n]['id'])
            albums[album]['name'].append(tracks['items'][n]['name'])
            albums[album]['uri'].append(tracks['items'][n]['uri'])
            albums[album]['duration_ms'].append(tracks['items'][n]['duration_ms'])
            albums[album]['preview_url'].append(tracks['items'][n]['preview_url'])

from google.colab import files
df = pd.DataFrame.from_dict(albums)
df.to_csv('Album_meta_data1.csv', sep=',')
files.download('Album_meta_data1.csv')

def audio_features(album):
    albums[album]['acousticness'] = []
    albums[album]['danceability'] = []
    albums[album]['energy'] = []
    albums[album]['instrumentalness'] = []
    albums[album]['liveness'] = []
    albums[album]['loudness'] = []
    albums[album]['speechiness'] = []
    albums[album]['tempo'] = []
    albums[album]['valence'] = []
    albums[album]['popularity'] = []
    
    track_count = 0
    for track in albums[album]['uri']:
        
        features = sp.audio_features(track)
        albums[album]['acousticness'].append(features[0]['acousticness'])
        albums[album]['danceability'].append(features[0]['danceability'])
        albums[album]['energy'].append(features[0]['energy'])
        albums[album]['instrumentalness'].append(features[0]['instrumentalness'])
        albums[album]['liveness'].append(features[0]['liveness'])
        albums[album]['loudness'].append(features[0]['loudness'])
        albums[album]['speechiness'].append(features[0]['speechiness'])
        albums[album]['tempo'].append(features[0]['tempo'])
        albums[album]['valence'].append(features[0]['valence'])
        
        pop = sp.track(track)
        albums[album]['popularity'].append(pop['popularity'])
        track_count+=1

import time
for i in albums:
    time.sleep(.5)
    audio_features(i)

dic_df = {}
dic_df['album'] = []
dic_df['track_number'] = []
dic_df['id'] = []
dic_df['name'] = []
dic_df['uri'] = []
dic_df['duration_ms'] = []
dic_df['acousticness'] = []
dic_df['danceability'] = []
dic_df['energy'] = []
dic_df['instrumentalness'] = []
dic_df['liveness'] = []
dic_df['loudness'] = []
dic_df['speechiness'] = []
dic_df['tempo'] = []
dic_df['valence'] = []
dic_df['popularity'] = []
dic_df['preview_url'] = []
for album in albums: 
    for feature in albums[album]:
        dic_df[feature].extend(albums[album][feature])
      
len(dic_df['album'])

dic_df

len(dic_df['acousticness'])

df = {'album': [], 'track_number': [], 'id': [], 'name': [], 'uri': [], 'duration_ms' : [], 'acousticness': [], 'danceability': [], 'energy': [], 'instrumentalness': [], 'liveness': [],
      'loudness': [], 'speechiness': [], 'tempo': [], 'valence': [], 'popularity': []}
df = pd.DataFrame.from_dict(dic_df)
df

df = df.drop_duplicates('id')
final_df = df.sort_values('popularity', ascending=False).sort_index()
final_df

from google.colab import files
final_df.to_csv('music.csv') 
files.download('music.csv')